In [25]:
from create_field import *
import numpy as np

**загрузка конфига визуализации**

In [26]:
with open(os.path.join('configs', 'cfg_vis.json'), 'r') as f:
    cfg = json.load(f)
    
cell_size = cfg['cell_size']
window_name = cfg['window_name']

**задание размера поля, типа соседства (Ring или Cross) и максимального кол-ва итераций**

In [27]:
neighbors_type = 'Ring'
field_size = 20
max_iterations = 100

**путь до директории, в которой будет создан конфиг**

In [28]:
new_cfg_path = os.path.join('configs', 'config_6')
if not os.path.exists(new_cfg_path):
    os.makedirs(new_cfg_path)

**создание изначальных мнений**

Открывается окно с полем. Можно нажимать на клетки, тем самым окрашивая их и задавая нужно мнение.

Выход нажатием любой клавиши на клавиатуре

In [29]:
grid_size = (field_size, field_size)
f = create_field(grid_size, cell_size, window_name)
print(f)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 1 1 1 1 0 1 0 0 0 1]
 [0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1]
 [0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1]
 [0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1]
 [0 0 1 0 0 1 0 1 0 0 1 1 1 1 0 1 0 0 0 1]
 [0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 1 0]
 [0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


**создание матрицы конформистов | нонконформистов | фиксированных**

0 = конформист | 1 = нонконформист | 2 - фиксированный

задается максимальное количество нонконформистов и фиксированных, которые случайно расставляются по полю

In [30]:
def create_matrix(grid_size, num_nonconf, num_fixed):
    
    matrix = np.zeros(grid_size, dtype=int)
    
    indices_ones = np.random.choice(400, num_nonconf, replace=False)
    matrix.ravel()[indices_ones] = 1

    indices_twos = np.random.choice(400, num_fixed, replace=False)
    matrix.ravel()[indices_twos] = 2
    
    return matrix

num_nonconf = 0
num_fixed = 10

matrix = create_matrix(grid_size, num_nonconf, num_fixed)
print(matrix)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 2 0]
 [2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 2 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


**Сохранение конфига**

In [31]:
new_config = {}

new_config['iterations'] = max_iterations
new_config['field_type'] = neighbors_type
new_config['field_size'] = field_size
new_config['field'] = str(f.tolist())
new_config['opinions'] = str(matrix.tolist())

with open(os.path.join(new_cfg_path, 'config.json'), 'w') as f:
    json.dump(new_config, f)