In [2]:
from create_field import *
import numpy as np

загрузка общего конфига

In [3]:
with open(os.path.join('configs', 'cfg.json'), 'r') as f:
    cfg = json.load(f)

In [4]:
grid_size = (cfg['grids_n'], cfg['grids_n'])
cell_size = cfg['cell_size']
window_name = cfg['window_name']

путь до директории, в которой будет создан конфиг

In [6]:
new_cfg_path = 'configs/config_4'
if not os.path.exists(new_cfg_path):
    os.makedirs(new_cfg_path)

создание изначальных мнений

открывается окно с полем. Можно нажимать на клетки, тем самым окрашивая их и задавая нужно мнение

итоговая матрица сохранится в json

In [8]:
f = create_field(grid_size, cell_size, window_name)

field_list = f.tolist()

with open(os.path.join(new_cfg_path, 'field.json'), 'w') as json_file:
    json.dump(field_list, json_file)

создание матрицы конформистов | нонконформистов | фиксированных

0 = конформист | 1 = нонконформист | 2 - фиксированный

задается максимальное количество нонконформистов и фиксированных, которые случайно расставляются по полю

In [5]:
def create_matrix(grid_size, num_nonconf, num_fixed):
    
    matrix = np.zeros(grid_size, dtype=int)
    
    indices_ones = np.random.choice(400, num_nonconf, replace=False)
    matrix.ravel()[indices_ones] = 1

    indices_twos = np.random.choice(400, num_fixed, replace=False)
    matrix.ravel()[indices_twos] = 2
    
    return matrix

num_nonconf = 60
num_fixed = 20

matrix = create_matrix(grid_size, num_nonconf, num_fixed)
print(matrix)


with open(os.path.join(new_cfg_path, 'opinion_matrix.json'), 'w') as json_file:
    json.dump(matrix.tolist(), json_file)

[[0 0 2 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 2 0 2 1 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 2 0 0 1 0 1 0 0 0 0 0 2 0 1]
 [1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 2 0 0]
 [0 0 1 0 1 0 2 0 0 0 1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 1 0 2 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 2 1 0 1 0 0 0 0 0 0 0 1]
 [1 1 1 1 0 0 0 0 0 0 2 0 0 1 2 0 0 0 0 0]
 [0 0 2 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 1 2 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 2 0 0 2 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0]]
